// Contract addresses and ABIs for Etherlink Testnet
export const CONTRACT_ADDRESSES = {
    EventFactory: "0x6885809b6894B8Dfa5BA92f01fEd1031E96007Ae" as const,
    TicketMarketplace: "0xFBC5f575A39D97a15545F095B92fA23BAa3ea075" as const,
    Registry: "0xDb3B9b7AC97D51D825aA43733D3f4aA49fe8B4Da" as const,
    RoyaltySplitterImpl: "0x9273391df6651941Fd02a674A5FB849e721F0094" as const,
};

export const EventFactoryABI = [
    {
        inputs: [
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "symbol", type: "string" },
            { internalType: "string", name: "venue", type: "string" },
            { internalType: "uint256", name: "eventDate", type: "uint256" },
            { internalType: "uint256", name: "ticketPrice", type: "uint256" },
            { internalType: "uint256", name: "maxSupply", type: "uint256" },
            { internalType: "string", name: "baseURI", type: "string" },
        ],
        name: "createEvent",
        outputs: [{ internalType: "address", name: "eventAddress", type: "address" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "symbol", type: "string" },
            { internalType: "string", name: "venue", type: "string" },
            { internalType: "uint256", name: "eventDate", type: "uint256" },
            { internalType: "uint256", name: "ticketPrice", type: "uint256" },
            { internalType: "uint256", name: "maxSupply", type: "uint256" },
            { internalType: "uint256", name: "maxTicketsPerWallet", type: "uint256" },
            { internalType: "uint256", name: "maxResalePercent", type: "uint256" },
            { internalType: "string", name: "baseURI", type: "string" },
            { internalType: "uint96", name: "royaltyPercent", type: "uint96" },
            { internalType: "address[]", name: "royaltyRecipients", type: "address[]" },
            { internalType: "uint256[]", name: "royaltyShares", type: "uint256[]" },
        ],
        name: "createEventAdvanced",
        outputs: [{ internalType: "address", name: "eventAddress", type: "address" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "getEvents",
        outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address[]", name: "eventAddresses", type: "address[]" }],
        name: "getMultipleEventInfo",
        outputs: [
            {
                components: [
                    { internalType: "uint256", name: "id", type: "uint256" },
                    { internalType: "address", name: "contractAddress", type: "address" },
                    { internalType: "address", name: "organizer", type: "address" },
                    { internalType: "string", name: "name", type: "string" },
                    { internalType: "string", name: "venue", type: "string" },
                    { internalType: "uint256", name: "eventDate", type: "uint256" },
                    { internalType: "uint256", name: "ticketPrice", type: "uint256" },
                    { internalType: "uint256", name: "maxSupply", type: "uint256" },
                    { internalType: "uint256", name: "createdAt", type: "uint256" },
                ],
                internalType: "struct EventFactory.EventInfo[]",
                name: "infos",
                type: "tuple[]",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "organizer", type: "address" }],
        name: "getEventsByOrganizer",
        outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "eventSplitter",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
] as const;


export const EventTicketABI = [
    {
        inputs: [],
        name: "purchaseTicket",
        outputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "quantity", type: "uint256" }],
        name: "purchaseTickets",
        outputs: [{ internalType: "uint256[]", name: "tokenIds", type: "uint256[]" }],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
        name: "verifyTicket",
        outputs: [
            { internalType: "bool", name: "isValid", type: "bool" },
            { internalType: "address", name: "holder", type: "address" },
            { internalType: "bool", name: "used", type: "bool" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "owner", type: "address" }],
        name: "getTicketsByOwner",
        outputs: [{ internalType: "uint256[]", name: "tokenIds", type: "uint256[]" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "ticketPrice",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "remainingTickets",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getEventDetails",
        outputs: [
            { internalType: "string", name: "name", type: "string" },
            { internalType: "string", name: "venue", type: "string" },
            { internalType: "uint256", name: "date", type: "uint256" },
            { internalType: "uint256", name: "price", type: "uint256" },
            { internalType: "uint256", name: "supply", type: "uint256" },
            { internalType: "uint256", name: "sold", type: "uint256" },
            { internalType: "address", name: "organizer", type: "address" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        name: "ticketUsed",
        outputs: [{ internalType: "bool", name: "", type: "bool" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "operator", type: "address" },
            { internalType: "bool", name: "approved", type: "bool" },
        ],
        name: "setApprovalForAll",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "tokenId", type: "uint256" },
        ],
        name: "approve",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    // Organizer functions
    {
        inputs: [],
        name: "withdrawFunds",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "string", name: "newBaseURI", type: "string" }],
        name: "setBaseURI",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
        name: "markAsUsed",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256[]", name: "tokenIds", type: "uint256[]" }],
        name: "batchMarkAsUsed",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [],
        name: "eventOrganizer",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "owner",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "baseTokenURI",
        outputs: [{ internalType: "string", name: "", type: "string" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalSold",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    // ERC721 transfer functions
    {
        inputs: [
            { internalType: "address", name: "from", type: "address" },
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "tokenId", type: "uint256" },
        ],
        name: "safeTransferFrom",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "from", type: "address" },
            { internalType: "address", name: "to", type: "address" },
            { internalType: "uint256", name: "tokenId", type: "uint256" },
        ],
        name: "transferFrom",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
] as const;


export const TicketMarketplaceABI = [
    {
        inputs: [
            { internalType: "address", name: "nftAddress", type: "address" },
            { internalType: "uint256", name: "tokenId", type: "uint256" },
            { internalType: "uint256", name: "price", type: "uint256" },
            { internalType: "address", name: "currency", type: "address" },
        ],
        name: "listTicket",
        outputs: [{ internalType: "uint256", name: "listingId", type: "uint256" }],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "listingId", type: "uint256" },
            { internalType: "uint256", name: "amountFromBalance", type: "uint256" },
        ],
        name: "buyTicket",
        outputs: [],
        stateMutability: "payable",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "listingId", type: "uint256" }],
        name: "cancelListing",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "uint256", name: "offset", type: "uint256" },
            { internalType: "uint256", name: "limit", type: "uint256" },
        ],
        name: "getActiveListings",
        outputs: [
            {
                components: [
                    { internalType: "uint256", name: "id", type: "uint256" },
                    { internalType: "uint256", name: "tokenId", type: "uint256" },
                    { internalType: "address", name: "nftAddress", type: "address" },
                    { internalType: "address", name: "seller", type: "address" },
                    { internalType: "address", name: "currency", type: "address" },
                    { internalType: "uint256", name: "price", type: "uint256" },
                    { internalType: "uint256", name: "createdAt", type: "uint256" },
                    { internalType: "bool", name: "active", type: "bool" },
                ],
                internalType: "struct TicketMarketplace.Listing[]",
                name: "activeListings",
                type: "tuple[]",
            },
            { internalType: "uint256", name: "total", type: "uint256" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "uint256", name: "listingId", type: "uint256" }],
        name: "getListing",
        outputs: [
            {
                components: [
                    { internalType: "uint256", name: "id", type: "uint256" },
                    { internalType: "uint256", name: "tokenId", type: "uint256" },
                    { internalType: "address", name: "nftAddress", type: "address" },
                    { internalType: "address", name: "seller", type: "address" },
                    { internalType: "address", name: "currency", type: "address" },
                    { internalType: "uint256", name: "price", type: "uint256" },
                    { internalType: "uint256", name: "createdAt", type: "uint256" },
                    { internalType: "bool", name: "active", type: "bool" },
                ],
                internalType: "struct TicketMarketplace.Listing",
                name: "",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "nftAddress", type: "address" },
            { internalType: "uint256", name: "tokenId", type: "uint256" },
            { internalType: "uint256", name: "price", type: "uint256" },
        ],
        name: "checkPriceCap",
        outputs: [
            { internalType: "bool", name: "valid", type: "bool" },
            { internalType: "uint256", name: "maxPrice", type: "uint256" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "currency", type: "address" }],
        name: "claimFunds",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "user", type: "address" },
            { internalType: "address", name: "currency", type: "address" },
        ],
        name: "claimableFunds",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
] as const;

export const RoyaltySplitterABI = [
    {
        inputs: [],
        name: "distribute",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [
            { internalType: "address", name: "marketplace", type: "address" },
            { internalType: "address", name: "currency", type: "address" },
        ],
        name: "claimAndDistribute",
        outputs: [],
        stateMutability: "nonpayable",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "account", type: "address" }],
        name: "pendingPayment",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "getRecipients",
        outputs: [
            { internalType: "address[]", name: "_recipients", type: "address[]" },
            { internalType: "uint256[]", name: "_shares", type: "uint256[]" },
        ],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "organizer",
        outputs: [{ internalType: "address", name: "", type: "address" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [],
        name: "totalReleased",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
    {
        inputs: [{ internalType: "address", name: "", type: "address" }],
        name: "released",
        outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
        stateMutability: "view",
        type: "function",
    },
] as const;
