export enum ErrorCode {
    WALLET_NOT_CONNECTED = "WALLET_NOT_CONNECTED",
    INSUFFICIENT_FUNDS = "INSUFFICIENT_FUNDS",
    TRANSACTION_REJECTED = "TRANSACTION_REJECTED",
    TRANSACTION_FAILED = "TRANSACTION_FAILED",
    CONTRACT_ERROR = "CONTRACT_ERROR",
    NETWORK_ERROR = "NETWORK_ERROR",
    TICKET_SOLD_OUT = "TICKET_SOLD_OUT",
    TICKET_ALREADY_USED = "TICKET_ALREADY_USED",
    INVALID_TICKET = "INVALID_TICKET",
    PRICE_EXCEEDS_CAP = "PRICE_EXCEEDS_CAP",
    UNAUTHORIZED = "UNAUTHORIZED",
}

export interface AppError {
    code: ErrorCode;
    message: string;
    details?: unknown;
}
